### ISSUE TITLE
Lunchbot prompts during weekends

### ISSUE THREAD

**Issue by ChristopherzwTan** [ChristopherzwTan/slack_memebot#2]
Lunchbot does not check for weekends when prompting for coffee.

**Comment by ChristopherzwTan** [comment]
Closed by @n-martin at commit: e180f1b

**Comment by n-martin** [comment]
Noice. 
+1

**Comment by ChristopherzwTan** [comment]
Haha, changes are in place. We'll see tomorrow how it'll fare.
