### ISSUE TITLE
Force Rosemary Rocksalt to be chosen on April 10th

### ISSUE THREAD

**Issue by henryymliu** [ChristopherzwTan/slack_memebot#24]
Nicole and I are thinking about dropping by on April 10th, and we would like to... let's say "bias" lunch to be at Rosemary Rocksalt on that day.

(I am also going to email Vincent about our visit, by the way, to make it a bit more official)

**Comment by ChristopherzwTan** [comment]
![accident](https://user-images.githubusercontent.com/5447843/37250160-fbde71dc-24aa-11e8-9e32-4b50b42f7d28.gif)

**Comment by ChristopherzwTan** [comment]
Didn't fix. Was too lazy to implement and we did not even go to Rosemary Rocksalt.
